apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-prometheus
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  local:
    path: /data/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: gluster-volume-mount/configured
          operator: In
          values:
          - "true"
        - key: gluster-volume-mount/ready
          operator: In
          values:
          - "true"
