apiVersion: v1
kind: ConfigMap
metadata:
  name: var-www
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="initial-scale=1.0">
    <style>
      body {
        text-align:center;
        font-family: sans-serif;
        font-size: 100%;
        background: black;
      }
      a {
        color: white;
      }
    </style>
    </head>
    <body>
      <p><a href="https://home.cambridge.me/">Home Assistant</a></p>
      <p>&nbsp;</p>
      <p><a href="https://jellyfin.home.cambridge.me">Jellyfin</a></p>
      <p>&nbsp;</p>
      <p><a href="https://radarr.home.cambridge.me">Radarr (movies)</a></p>
      <p><a href="https://sonarr.home.cambridge.me">Sonarr (tv shows)</a></p>
      <p>&nbsp;</p>
      <p><a href="https://jackett.home.cambridge.me">Jackett</a></p>
      <p><a href="https://transmission.home.cambridge.me">Transmission</a></p>
      <p><a href="https://nzbget.home.cambridge.me">NZBGet</a></p>
      <p>&nbsp;</p>
      <p><a href="https://openwrt.lan/">OpenWRT</a></p>
      <p><a href="https://openwrt.lan:8443/">Unifi</a></p>
      <p><a href="https://ldap.home.cambridge.me/">LDAP</a></p>
      <p><a href="https://esphome.home.cambridge.me">esphome</a></p>
    </body>
    </html>
